### PR TITLE
Switch from Prettier to Biome

### PR DESCRIPTION
**Pull request by jacobdalamb**
Switch from Prettier to [Biome](https://biomejs.dev/) for formatting and linting.

Theres a lot more lint errors that I didn't fix and also got this message:

```
The number of diagnostics exceeds the number allowed by Biome.
Diagnostics not shown: 364.
Checked 64 file(s) in 36ms
Found 122 error(s)
```

### CODE REVIEW

**Comment by ubmit** [comment]
I think that the PR title is a bit misleading. It isn't really about fixing errors, it's about switching from Prettier to Biome

**Comment by jjenzz** [comment]
@jacobdalamb can you help me understand why this PR is necessary? i am happy with prettier and the rules i had used and this appears to removes many of my purposefully chosen preferences.

**Comment by jacobdalamb** [comment]
> @jacobdalamb can you help me understand why this PR is necessary? i am happy with prettier and the rules i had used. this appears to removes many of my purposefully chosen preferences.

My proposal for Biome is based on its ability to offer several advantages that could be beneficial for this project.

- Enhanced Linting Capabilities: Biome integrates additional linting rules that were previously not in place. This could help maintain a higher code quality and consistency.

- Compatibility with Prettier: While introducing new features, Biome maintains over 96% compatibility with Prettier, as detailed in this [blog post](https://biomejs.dev/blog/biome-wins-prettier-challenge/). This means you can retain most of the formatting preferences you've carefully chosen, while also benefiting from Biome's extended capabilities.

 However, I completely respect your preferences and the existing setup.

**Comment by jjenzz** [comment]
@jacobdalamb i would propose opening a GH issue for things like this in future so that we can discuss before beginning work on things. as it stands, this is not something i feel the project immediately requires, especially since i have not used biome before. 

thanks for your interest in contributing though. if you'd like to raise an issue listing the lint rules you think this project needs, i can perhaps consider Biome in the future or add them to prettier if agreed.

**Pull request closed without merging**
